<?php 
$title = 'Sign up';
$this->headtitle($title);
?>

<h3><?= $this->escapehtml($title); ?></h3>

<?php 
    
    $form = $this->form;
    $form->setAttribute('action', $this->url('user', array('action' => 'signup')));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo '<dl class="zend_form">';
    echo $this->formHidden($form->get('id'));
    echo '<dt>' . $this->formLabel($form->get('username')) . '</dt>';
    echo '<dd>';
    echo $this->formInput($form->get('username'));
    echo $this->formElementErrors($form->get('username'));
    echo '</dd>';
    echo '<dt>' . $this->formLabel($form->get('password')) . '</dt>';
    echo '<dd>';
    echo $this->formInput($form->get('password'));
    echo $this->formElementErrors($form->get('password'));
    echo '</dd>';
    echo '<dd>';
    echo $this->formsubmit($form->get('submit')->setAttribute('class', 'btn btn-success'));
    echo '</dd>';
    echo '<dl>';
    echo $this->form()->closeTag();
?>
