<div class="hero-unit">
    <p><a class="btn btn-success btn-large" href="<?= $this->url('user'); ?>"><?= $this->translate('ZF2-Auth Module'); ?></a>
    <p><a class="btn btn-success btn-large" href="https://github.com/FlorentinTh/ZF2-Auth"><?= $this->translate('Fork me on GitHub') ?> &raquo;</a></p>
    <p><a class="btn btn-success btn-large" href="https://github.com/zendframework/zf2"><?= $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
</div>
